ain-ar:
  isol: [ain.isol.skl]
  init: [ain.init.skl]
  medi: [ain.medi.skl]
  fina: [ain.fina.skl]
ainThreedots-ar:
  isol: [ain.isol.skl, threedotabove.mrk]
  init: [ain.init.skl, threedotabove.mrk]
  medi: [ain.medi.skl, threedotabove.mrk]
  fina: [ain.fina.skl, threedotabove.mrk]
alef-ar:
  isol: [alef.isol.skl]
  fina: [alef.fina.skl]
alefHamzaabove-ar:
  isol: [alef.isol.skl, hamza.mrk]
  fina: [alef.fina.skl, hamza.mrk]
alefHamzabelow-ar:
  isol: [alef.isol.skl, hamza.mrk]
  fina: [alef.fina.skl, hamza.mrk]
alefMadda-ar:
  isol: [alef.isol.skl, madda.mrk]
  fina: [alef.fina.skl, madda.mrk]
alefMaksura-ar:
  isol: [yeh.isol.skl]
  fina: [yeh.fina.skl]
alefWavyhamzaabove-ar:
  isol: [alef.isol.skl, wavyhamzaabove.mrk]
  fina: [alef.fina.skl, wavyhamzaabove.mrk]
alefWavyhamzabelow-ar:
  isol: [alef.isol.skl, wavyhamzabelow.mrk]
  fina: [alef.fina.skl, wavyhamzabelow.mrk]
beeh-ar:
  isol: [behDotless.isol.skl, V-twodotbelow.mrk]
  init: [behDotless.init.skl, V-twodotbelow.mrk]
  medi: [behDotless.medi.skl, V-twodotbelow.mrk]
  fina: [behDotless.fina.skl, V-twodotbelow.mrk]
beh-ar:
  isol: [behDotless.isol.skl, dotabove.mrk]
  init: [behDotless.init.skl, dotbelow.mrk]
  medi: [behDotless.medi.skl]
  fina: [behDotless.fina.skl]
behDotless-ar:
  isol: [behDotless.isol.skl]
  init: [behDotless.init.skl]
  medi: [behDotless.medi.skl]
  fina: [behDotless.fina.skl]
beheh-ar:
  isol: [behDotless.isol.skl, fourdotbelow.mrk]
  init: [behDotless.init.skl, fourdotbelow.mrk]
  medi: [behDotless.medi.skl, fourdotbelow.mrk]
  fina: [behDotless.fina.skl, fourdotbelow.mrk]
dad-ar:
  isol: [sad.isol.skl, dotabove.mrk]
  init: [sad.init.skl, dotabove.mrk]
  medi: [sad.medi.skl, dotabove.mrk]
  fina: [sad.fina.skl, dotabove.mrk]
dadDotbelow-ar:
  isol: [sad.isol.skl, dotabove.mrk, dotbelow.mrk]
  init: [sad.init.skl, dotabove.mrk, dotbelow.mrk]
  medi: [sad.medi.skl, dotabove.mrk, dotbelow.mrk]
  fina: [sad.fina.skl, dotabove.mrk, dotbelow.mrk]
dahal-ar:
  isol: [dal.isol.skl, H]
  fina: [dal.fins.skl, H]
dal-ar:
  isol: [dal.isol.skl]
  fina: [dal.fins.skl]
dalDotbelow-ar:
  isol: [dal.isol.skl, dotbelow.mrk]
  fina: [dal.fins.skl, dotbelow.mrk]
dalDotbelowTah-ar:
  isol: [dal.isol.skl, tahabove.mrk, dotbelow.mrk]
  fina: [dal.fins.skl, tahabove.mrk, dotbelow.mrk]
dalFourdots-ar:
  isol: [dal.isol.skl, fourdotabove.mrk]
  fina: [dal.fins.skl, fourdotabove.mrk]
dalRing-ar:
  isol: [dal.isol.skl, ring.mrk]
  fina: [dal.fins.skl, ring.mrk]
dalThreedotsdown-ar:
  isol: [dal.isol.skl, R-threedotabove.mrk]
  fina: [dal.fins.skl, R-threedotabove.mrk]
dalVinvertedabove-ar:
  isol: [dal.isol.skl, vinvertedabove.mrk]
  fina: [dal.fins.skl, vinvertedabove.mrk]
ddahal-ar:
  isol: [dal.isol.skl, H-twodotbelow.mrk]
  fina: [dal.fins.skl, H-twodotbelow.mrk]
ddal-ar:
  isol: [dal.isol.skl, tahabove.mrk]
  fina: [dal.fins.skl, tahabove.mrk]
dotaboveSymbol-ar:
  isol: [dotabove.mrk]
dotbelowSymbol-ar:
  isol: [dotbelow.mrk]
doubleverticalbarbelowSymbol-ar:
  isol: [V-twodotbelow.mrk]
dul-ar:
  isol: [dal.isol.skl, threedotabove.mrk]
  fina: [dal.fins.skl, threedotabove.mrk]
dyeh-ar:
  isol: [hah.isol.skl, V-twodotbelow.mrk]
  init: [hah.init.skl, V-twodotbelow.mrk]
  medi: [hah.medi.skl, V-twodotbelow.mrk]
  fina: [hah.fina.skl, V-twodotbelow.mrk]
e-ar:
  isol: [waw.isol.skl, V-twodotbelow.mrk]
  fina: [waw.fina.skl, V-twodotbelow.mrk]
feh-ar:
  isol: [fehDotless.isol.skl, dotabove.mrk]
  init: [fehDotless.init.skl, dotabove.mrk]
  medi: [fehDotless.medi.skl, dotabove.mrk]
  fina: [fehDotless.fina.skl, dotabove.mrk]
fehDotbelow-ar:
  isol: [fehDotless.isol.skl, dotabove.mrk, dotbelow.mrk]
  init: [fehDotless.init.skl, dotabove.mrk, dotbelow.mrk]
  medi: [fehDotless.medi.skl, dotabove.mrk, dotbelow.mrk]
  fina: [fehDotless.fina.skl, dotabove.mrk, dotbelow.mrk]
fehDotless-ar:
  isol: [fehDotless.isol.skl]
  init: [fehDotless.init.skl]
  medi: [fehDotless.medi.skl]
  fina: [fehDotless.fina.skl]
fehDotmovedbelow-ar:
  isol: [fehDotless.isol.skl, dotbelow.mrk]
  init: [fehDotless.init.skl, dotbelow.mrk]
  medi: [fehDotless.medi.skl, dotbelow.mrk]
  fina: [fehDotless.fina.skl, dotbelow.mrk]
fehThreedotsbelow-ar:
  isol: [fehDotless.isol.skl, threedotbelow.mrk]
  init: [fehDotless.init.skl, threedotbelow.mrk]
  medi: [fehDotless.medi.skl, threedotbelow.mrk]
  fina: [fehDotless.fina.skl, threedotbelow.mrk]
fourdotsaboveSymbol-ar:
  isol: [fourdotabove.mrk]
fourdotsbelowSymbol-ar:
  isol: [fourdotbelow.mrk]
gaf-ar:
  isol: [keheh.isol.skl, sarkesh.mrk]
  init: [keheh.init.skl, sarkesh.mrk]
  medi: [keheh.medi.skl, sarkesh.mrk]
  fina: [keheh.fina.skl, sarkesh.mrk]
gafRing-ar:
  isol: [keheh.isol.skl, sarkesh.mrk, ring.mrk]
  init: [keheh.init.skl, sarkesh.mrk, ring.mrk]
  medi: [keheh.medi.skl, sarkesh.mrk, ring.mrk]
  fina: [keheh.fina.skl, sarkesh.mrk, ring.mrk]
gafThreedots-ar:
  isol: [keheh.isol.skl, sarkesh.mrk, threedotabove.mrk]
  init: [keheh.init.skl, sarkesh.mrk, threedotabove.mrk]
  medi: [keheh.medi.skl, sarkesh.mrk, threedotabove.mrk]
  fina: [keheh.fina.skl, sarkesh.mrk, threedotabove.mrk]
gafTwodotsbelow-ar:
  isol: [keheh.isol.skl, sarkesh.mrk, H-twodotbelow.mrk]
  init: [keheh.init.skl, sarkesh.mrk, H-twodotbelow.mrk]
  medi: [keheh.medi.skl, sarkesh.mrk, H-twodotbelow.mrk]
  fina: [keheh.fina.skl, sarkesh.mrk, H-twodotbelow.mrk]
ghain-ar:
  isol: [ain.isol.skl, dotabove.mrk]
  init: [ain.init.skl, dotabove.mrk]
  medi: [ain.medi.skl, dotabove.mrk]
  fina: [ain.fina.skl, dotabove.mrk]
ghainDotbelow-ar:
  isol: [ain.isol.skl, dotabove.mrk, dotbelow.mrk]
  init: [ain.init.skl, dotabove.mrk, dotbelow.mrk]
  medi: [ain.medi.skl, dotabove.mrk, dotbelow.mrk]
  fina: [ain.fina.skl, dotabove.mrk, dotbelow.mrk]
gueh-ar:
  isol: [keheh.isol.skl, sarkesh.mrk, V-twodotbelow.mrk]
  init: [keheh.init.skl, sarkesh.mrk, V-twodotbelow.mrk]
  medi: [keheh.medi.skl, sarkesh.mrk, V-twodotbelow.mrk]
  fina: [keheh.fina.skl, sarkesh.mrk, V-twodotbelow.mrk]
hah-ar:
  isol: [hah.isol.skl]
  init: [hah.init.skl]
  medi: [hah.medi.skl]
  fina: [hah.fina.skl]
hahHamzaabove-ar:
  isol: [hah.isol.skl, hamza.mrk]
  init: [hah.init.skl, hamza.mrk]
  medi: [hah.medi.skl, hamza.mrk]
  fina: [hah.fina.skl, hamza.mrk]
hahThreedotsabove-ar:
  isol: [hah.isol.skl, threedotabove.mrk]
  init: [hah.init.skl, threedotabove.mrk]
  medi: [hah.medi.skl, threedotabove.mrk]
  fina: [hah.fina.skl, threedotabove.mrk]
hahTwodotsverticalabove-ar:
  isol: [hah.isol.skl, V-twodotabove.mrk]
  init: [hah.init.skl, V-twodotabove.mrk]
  medi: [hah.medi.skl, V-twodotabove.mrk]
  fina: [hah.fina.skl, V-twodotabove.mrk]
hamza-ar:
  isol: [hamza.mrk]
heh-ar:
  isol: [heh.isol.skl]
  init: [heh.init.skl]
  medi: [heh.medi.skl]
  fina: [heh.fina.skl]
hehDoachashmee-ar:
  isol: [hehDoachashmee.isol.skl]
  init: [hehDoachashmee.init.skl]
  medi: [hehDoachashmee.medi.skl]
  fina: [hehDoachashmee.fina.skl]
hehHamzaabove-ar:
  isol: [heh.isol.skl, aboweyeh.mrk]
  init: [heh.init.skl, aboweyeh.mrk]
  medi: [heh.medi.skl, aboweyeh.mrk]
  fina: [heh.fina.skl, aboweyeh.mrk]
hehVinvertedabove-ar:
  isol: [hehDoachashmee.isol.skl, vinvertedabove.mrk]
  fina: [hehDoachashmee.fina.skl, vinvertedabove.mrk]
hehgoal-ar:
  isol: [heh.isol.skl]
  init: [hehgoal.init.skl]
  medi: [hehgoal.medi.skl]
  fina: [heh.fina.skl]
hehgoalHamzaabove-ar:
  isol: [hehgoal.isol.skl, hamza.mrk]
  init: [hehgoal.init.skl, hamza.mrk]
  medi: [hehgoal.medi.skl, hamza.mrk]
  fina: [hehgoal.fina.skl, hamza.mrk]
jeem-ar:
  isol: [hah.isol.skl, dotbelow.mrk]
  init: [hah.init.skl, dotbelow.mrk]
  medi: [hah.medi.skl, dotbelow.mrk]
  fina: [hah.fina.skl, dotbelow.mrk]
jeh-ar:
  isol: [reh.isol.skl, threedotabove.mrk]
  fina: [reh.fina.skl, threedotabove.mrk]
kaf-ar:
  isol: [kaf.isol.skl]
  init: [keheh.init.skl]
  medi: [keheh.medi.skl]
  fina: [kaf.fina.skl]
kafDotabove-ar:
  isol: [kaf.isol.skl, dotabove.mrk]
  init: [keheh.init.skl, dotabove.mrk]
  medi: [keheh.medi.skl, dotabove.mrk]
  fina: [kaf.fina.skl, dotabove.mrk]
kafRing-ar:
  isol: [kaf.isol.skl, ring.mrk]
  init: [kaf.init.skl, ring.mrk]
  medi: [kaf.medi.skl, ring.mrk]
  fina: [kaf.fina.skl, ring.mrk]
kafThreedotsbelow-ar:
  isol: [kaf.isol.skl, threedotbelow.mrk]
  init: [keheh.init.skl, threedotbelow.mrk]
  medi: [keheh.medi.skl, threedotbelow.mrk]
  fina: [kaf.fina.skl, threedotbelow.mrk]
keheh-ar:
  isol: [keheh.isol.skl]
  init: [keheh.init.skl]
  medi: [keheh.medi.skl]
  fina: [keheh.fina.skl]
kehehThreedotsbelow-ar:
  isol: [keheh.isol.skl, threedotbelow.mrk]
  init: [keheh.init.skl, threedotbelow.mrk]
  medi: [keheh.medi.skl, threedotbelow.mrk]
  fina: [keheh.fina.skl, threedotbelow.mrk]
kehehTwodotshorizontalabove-ar:
  isol: [keheh.isol.skl, H-twodotabove.mrk]
  init: [keheh.init.skl, H-twodotabove.mrk]
  medi: [keheh.medi.skl, H-twodotabove.mrk]
  fina: [keheh.fina.skl, H-twodotabove.mrk]
khah-ar:
  isol: [hah.isol.skl, dotabove.mrk]
  init: [hah.init.skl, dotabove.mrk]
  medi: [hah.medi.skl, dotabove.mrk]
  fina: [hah.fina.skl, dotabove.mrk]
kirghizyu-ar:
  isol: [waw.isol.skl, H]
  fina: [waw.fina.skl, H]
lam-ar:
  isol: [lam.isol.skl]
  init: [lam.init.skl]
  medi: [lam.medi.skl]
  fina: [lam.fina.skl]
lamDotabove-ar:
  isol: [lam.isol.skl, dotabove.mrk]
  init: [lam.init.skl, dotabove.mrk]
  medi: [lam.medi.skl, dotabove.mrk]
  fina: [lam.fina.skl, dotabove.mrk]
lamThreedotsabove-ar:
  isol: [lam.isol.skl, threedotabove.mrk]
  init: [lam.init.skl, threedotabove.mrk]
  medi: [lam.medi.skl, threedotabove.mrk]
  fina: [lam.fina.skl, threedotabove.mrk]
lamThreedotsbelow-ar:
  isol: [lam.isol.skl, threedotbelow.mrk]
  init: [lam.init.skl, threedotbelow.mrk]
  medi: [lam.medi.skl, threedotbelow.mrk]
  fina: [lam.fina.skl, threedotbelow.mrk]
lamVabove-ar:
  isol: [lam.isol.skl, vabove.mrk]
  init: [lam.init.skl, vabove.mrk]
  medi: [lam.medi.skl, vabove.mrk]
  fina: [lam.fina.skl, vabove.mrk]
meem-ar:
  isol: [meem.isol.skl]
  init: [meem.init.skl]
  medi: [meem.medi.skl]
  fina: [meem.fina.skl]
ng-ar:
  isol: [kaf.isol.skl, threedotabove.mrk]
  init: [keheh.init.skl, threedotabove.mrk]
  medi: [keheh.medi.skl, threedotabove.mrk]
  fina: [kaf.fina.skl, threedotabove.mrk]
ngoeh-ar:
  isol: [keheh.isol.skl, sarkesh.mrk, H]
  init: [keheh.init.skl, sarkesh.mrk, H]
  medi: [keheh.medi.skl, sarkesh.mrk, H]
  fina: [keheh.fina.skl, sarkesh.mrk, H]
noon-ar:
  isol: [noon.isol.skl, dotabove.mrk]
  init: [behDotless.init.skl, dotabove.mrk]
  medi: [behDotless.medi.skl, dotabove.mrk]
  fina: [noon.fina.skl, dotabove.mrk]
noonDotbelow-ar:
  isol: [noon.isol.skl, dotabove.mrk, dotbelow.mrk]
  init: [behDotless.init.skl, dotabove.mrk, dotbelow.mrk]
  medi: [behDotless.medi.skl, dotabove.mrk, dotbelow.mrk]
  fina: [noon.fina.skl, dotabove.mrk, dotbelow.mrk]
noonRing-ar:
  isol: [noon.isol.skl, dotabove.mrk, ring.mrk]
  init: [behDotless.init.skl, dotabove.mrk, ring.mrk]
  medi: [behDotless.medi.skl, dotabove.mrk, ring.mrk]
  fina: [noon.fina.skl, dotabove.mrk, ring.mrk]
noonThreedotsabove-ar:
  isol: [noon.isol.skl, threedotabove.mrk]
  init: [noon.init.skl, threedotabove.mrk]
  medi: [noon.medi.skl, threedotabove.mrk]
  fina: [noon.fina.skl, threedotabove.mrk]
noonghunna-ar:
  isol: [noon.isol.skl, tahabove.mrk]
  init: [behDotless.init.skl, tahabove.mrk]
  medi: [behDotless.medi.skl, tahabove.mrk]
  fina: [noon.fina.skl, tahabove.mrk]
nyeh-ar:
  isol: [hah.isol.skl, H-twodotbelow.mrk]
  init: [hah.init.skl, H-twodotbelow.mrk]
  medi: [hah.medi.skl, H-twodotbelow.mrk]
  fina: [hah.fina.skl, H-twodotbelow.mrk]
oe-ar:
  isol: [waw.isol.skl, vabove.mrk]
  fina: [waw.fina.skl, vabove.mrk]
peh-ar:
  isol: [behDotless.isol.skl, threedotbelow.mrk]
  init: [behDotless.init.skl, threedotbelow.mrk]
  medi: [behDotless.medi.skl, threedotbelow.mrk]
  fina: [behDotless.fina.skl, threedotbelow.mrk]
peheh-ar:
  isol: [fehDotless.isol.skl, fourdotabove.mrk]
  init: [fehDotless.init.skl, fourdotabove.mrk]
  medi: [fehDotless.medi.skl, fourdotabove.mrk]
  fina: [fehDotless.fina.skl, fourdotabove.mrk]
qaf-ar:
  isol: [qafDotless.isol.skl, H]
  init: [fehDotless.init.skl, H]
  medi: [fehDotless.medi.skl, H]
  fina: [qafDotless.fina.skl, H]
qafDotabove-ar:
  isol: [qafDotless.isol.skl, dotabove.mrk]
  init: [fehDotless.init.skl, dotabove.mrk]
  medi: [fehDotless.medi.skl, dotabove.mrk]
  fina: [qafDotless.fina.skl, dotabove.mrk]
qafThreedotsabove-ar:
  isol: [qafDotless.isol.skl, threedotabove.mrk]
  init: [fehDotless.init.skl, threedotabove.mrk]
  medi: [fehDotless.medi.skl, threedotabove.mrk]
  fina: [qafDotless.fina.skl, threedotabove.mrk]
reh-ar:
  isol: [reh.isol.skl]
  fina: [reh.fina.skl]
rehDotbelow-ar:
  isol: [reh.isol.skl, dotbelow.mrk]
  fina: [reh.fina.skl, dotbelow.mrk]
rehDotbelowdotabove-ar:
  isol: [rehDotbelowdotabove.isol.skl, dotabove.mrk]
  fina: [rehDotbelowdotabove.fina.skl, dotabove.mrk]
rehFourdots-ar:
  isol: [reh.isol.skl, fourdotabove.mrk]
  fina: [reh.fina.skl, fourdotabove.mrk]
rehRing-ar:
  isol: [reh.isol.skl, ring.mrk]
  fina: [reh.fina.skl, ring.mrk]
rehTwodots-ar:
  isol: [reh.isol.skl, H]
  fina: [reh.fina.skl, H]
rehVbelow-ar:
  isol: [reh.isol.skl, vbelow.mrk]
  fina: [reh.fina.skl, vbelow.mrk]
rehVinvertedabove-ar:
  isol: [reh.isol.skl, vinvertedabove.mrk]
  fina: [reh.fina.skl, vinvertedabove.mrk]
rehv-ar:
  isol: [reh.isol.skl, vabove.mrk]
  fina: [reh.fina.skl, vabove.mrk]
ringSymbol-ar:
  isol: [ring.mrk]
rreh-ar:
  isol: [reh.isol.skl, tahabove.mrk]
  fina: [reh.fina.skl, tahabove.mrk]
sad-ar:
  isol: [sad.isol.skl]
  init: [sad.init.skl]
  medi: [sad.medi.skl]
  fina: [sad.fina.skl]
sadThreedots-ar:
  isol: [sad.isol.skl, threedotabove.mrk]
  init: [sad.init.skl, threedotabove.mrk]
  medi: [sad.medi.skl, threedotabove.mrk]
  fina: [sad.fina.skl, threedotabove.mrk]
sadTwodotsbelow-ar:
  isol: [sad.isol.skl, H-twodotbelow.mrk]
  init: [sad.init.skl, H-twodotbelow.mrk]
  medi: [sad.medi.skl, H-twodotbelow.mrk]
  fina: [sad.fina.skl, H-twodotbelow.mrk]
seen-ar:
  isol: [seen.isol.skl]
  init: [seen.init.skl]
  medi: [seen.medi.skl]
  fina: [seen.fina.skl]
seenDotbelowDotabove-ar:
  isol: [seen.isol.skl, dotbelow.mrk, dotabove.mrk]
  init: [seen.init.skl, dotbelow.mrk, dotabove.mrk]
  medi: [seen.medi.skl, dotbelow.mrk, dotabove.mrk]
  fina: [seen.fina.skl, dotbelow.mrk, dotabove.mrk]
seenThreedotsbelow-ar:
  isol: [seen.isol.skl, threedotbelow.mrk]
  init: [seen.init.skl, threedotbelow.mrk]
  medi: [seen.medi.skl, threedotbelow.mrk]
  fina: [seen.fina.skl, threedotbelow.mrk]
sheen-ar:
  isol: [seen.isol.skl, threedotabove.mrk]
  init: [seen.init.skl, threedotabove.mrk]
  medi: [seen.medi.skl, threedotabove.mrk]
  fina: [seen.fina.skl, threedotabove.mrk]
sheenDotbelow-ar:
  isol: [seen.isol.skl, threedotabove.mrk, dotbelow.mrk]
  init: [seen.init.skl, threedotabove.mrk, dotbelow.mrk]
  medi: [seen.medi.skl, threedotabove.mrk, dotbelow.mrk]
  fina: [seen.fina.skl, threedotabove.mrk, dotbelow.mrk]
sheenThreedotsbelow-ar:
  isol: [seen.isol.skl, threedotbelow.mrk, threedotabove.mrk]
  init: [seen.init.skl, threedotbelow.mrk, threedotabove.mrk]
  medi: [seen.medi.skl, threedotbelow.mrk, threedotabove.mrk]
  fina: [seen.fina.skl, threedotbelow.mrk, threedotabove.mrk]
tah-ar:
  isol: [tah.isol.skl]
  init: [tah.init.skl]
  medi: [tah.medi.skl]
  fina: [tah.fina.skl]
tahThreedots-ar:
  isol: [tah.isol.skl, threedotabove.mrk]
  init: [tah.init.skl, threedotabove.mrk]
  medi: [tah.medi.skl, threedotabove.mrk]
  fina: [tah.fina.skl, threedotabove.mrk]
tahaboveSymbol-ar:
  isol: [tahabove.mrk]
tahbelowSymbol-ar:
  isol: [tahbelow.mrk]
tcheh-ar:
  isol: [hah.isol.skl, threedotbelow.mrk]
  init: [hah.init.skl, threedotbelow.mrk]
  medi: [hah.medi.skl, threedotbelow.mrk]
  fina: [hah.fina.skl, threedotbelow.mrk]
tchehDotabove-ar:
  isol: [hah.isol.skl, threedotbelow.mrk, dotabove.mrk]
  init: [hah.init.skl, threedotbelow.mrk, dotabove.mrk]
  medi: [hah.medi.skl, threedotbelow.mrk, dotabove.mrk]
  fina: [hah.fina.skl, threedotbelow.mrk, dotabove.mrk]
tcheheh-ar:
  isol: [hah.isol.skl, fourdotbelow.mrk]
  init: [hah.init.skl, fourdotbelow.mrk]
  medi: [hah.medi.skl, fourdotbelow.mrk]
  fina: [hah.fina.skl, fourdotbelow.mrk]
teh-ar:
  isol: [behDotless.isol.skl, H]
  init: [behDotless.init.skl, H]
  medi: [behDotless.medi.skl, H]
  fina: [behDotless.fina.skl, H]
tehMarbuta-ar:
  isol: [heh.isol.skl, H]
  fina: [heh.fina.skl, H]
tehRing-ar:
  isol: [behDotless.isol.skl, H, ring.mrk]
  init: [behDotless.init.skl, H, ring.mrk]
  medi: [behDotless.medi.skl, H, ring.mrk]
  fina: [behDotless.fina.skl, H, ring.mrk]
tehThreedotsdown-ar:
  isol: [behDotless.isol.skl, R-threedotabove.mrk]
  init: [behDotless.init.skl, R-threedotabove.mrk]
  medi: [behDotless.medi.skl, R-threedotabove.mrk]
  fina: [behDotless.fina.skl, R-threedotabove.mrk]
teheh-ar:
  isol: [fehDotless.isol.skl, fourdotabove.mrk]
  init: [fehDotless.init.skl, fourdotabove.mrk]
  medi: [fehDotless.medi.skl, fourdotabove.mrk]
  fina: [fehDotless.fina.skl, fourdotabove.mrk]
thal-ar:
  isol: [dal.isol.skl, dotabove.mrk]
  fina: [dal.fins.skl, dotabove.mrk]
theh-ar:
  isol: [behDotless.isol.skl, threedotabove.mrk]
  init: [behDotless.init.skl, threedotabove.mrk]
  medi: [behDotless.medi.skl, threedotabove.mrk]
  fina: [behDotless.fina.skl, threedotabove.mrk]
threedotsdownaboveSymbol-ar:
  isol: [R-threedotabove.mrk]
threedotsdownbelowSymbol-ar:
  isol: [R-threedotbelow.mrk]
threedotsupaboveSymbol-ar:
  isol: [threedotabove.mrk]
threedotsupbelowSymbol-ar:
  isol: [threedotbelow.mrk]
tteh-ar:
  isol: [behDotless.isol.skl, tahabove.mrk]
  init: [behDotless.init.skl, tahabove.mrk]
  medi: [behDotless.medi.skl, tahabove.mrk]
  fina: [behDotless.fina.skl, tahabove.mrk]
tteheh-ar:
  isol: [behDotless.isol.skl, V-twodotabove.mrk]
  init: [behDotless.init.skl, V-twodotabove.mrk]
  medi: [behDotless.medi.skl, V-twodotabove.mrk]
  fina: [behDotless.fina.skl, V-twodotabove.mrk]
twodotshorizontalaboveSymbol-ar:
  isol: [H-twodotabove.mrk]
twodotshorizontalbelowSymbol-ar:
  isol: [H-twodotbelow.mrk]
twodotsverticalaboveSymbol-ar:
  isol: [V-twodotabove.mrk]
twodotsverticalbelowSymbol-ar:
  isol: [V-twodotbelow.mrk]
ve-ar:
  isol: [waw.isol.skl, vabove.mrk]
  fina: [waw.fina.skl, vabove.mrk]
veh-ar:
  isol: [fehDotless.isol.skl, threedotabove.mrk]
  init: [fehDotless.init.skl, threedotabove.mrk]
  medi: [fehDotless.medi.skl, threedotabove.mrk]
  fina: [fehDotless.fina.skl, threedotabove.mrk]
waw-ar:
  isol: [waw.isol.skl]
  fina: [waw.fina.skl]
wawDotabove-ar:
  isol: [waw.isol.skl, dotabove.mrk]
  fina: [waw.fina.skl, dotabove.mrk]
wawHamzaabove-ar:
  isol: [waw.isol.skl, hamza.mrk]
  fina: [waw.fina.skl, hamza.mrk]
wawTwodots-ar:
  isol: [waw.isol.skl, H]
  fina: [waw.fina.skl, H]
wawring-ar:
  isol: [waw.isol.skl, ring.mrk]
  fina: [waw.fina.skl, ring.mrk]
yeh-ar:
  isol: [yeh.isol.skl, H-twodotbelow.mrk]
  init: [behDotless.init.skl, H-twodotbelow.mrk]
  medi: [behDotless.medi.skl, H-twodotbelow.mrk]
  fina: [yeh.fina.skl, H-twodotbelow.mrk]
yeh-farsi:
  isol: [yeh.isol.skl]
  init: [behDotless.init.skl, H-twodotbelow.mrk]
  medi: [behDotless.medi.skl, H-twodotbelow.mrk]
  fina: [yeh.fina.skl]
yehHamzaabove-ar:
  isol: [yeh.isol.skl, hamza.mrk]
  init: [yeh.init.skl, hamza.mrk]
  medi: [yeh.medi.skl, hamza.mrk]
  fina: [yeh.fina.skl, hamza.mrk]
yehThreedotsabove-farsi:
  isol: [yeh.isol.skl, threedotabove.mrk]
  init: [yeh.init.skl, threedotabove.mrk]
  medi: [yeh.medi.skl, threedotabove.mrk]
  fina: [yeh.fina.skl, threedotabove.mrk]
yehThreedotsbelow-ar:
  isol: [yeh.isol.skl, threedotbelow.mrk]
  fina: [yeh.fina.skl, threedotbelow.mrk]
yehTwodotsabove-farsi:
  isol: [yeh.isol.skl, H-twodotabove.mrk]
  init: [yeh.init.skl, H-twodotabove.mrk]
  medi: [yeh.medi.skl, H-twodotabove.mrk]
  fina: [yeh.fina.skl, H-twodotabove.mrk]
yehVabove-ar:
  isol: [yeh.isol.skl, vabove.mrk]
  init: [yeh.init.skl, vabove.mrk]
  medi: [yeh.medi.skl, vabove.mrk]
  fina: [yeh.fina.skl, vabove.mrk]
yehVinverted-farsi:
  isol: [yeh.isol.skl, vinvertedabove.mrk]
  init: [yeh.init.skl, vinvertedabove.mrk]
  medi: [yeh.medi.skl, vinvertedabove.mrk]
  fina: [yeh.fina.skl, vinvertedabove.mrk]
yehbarree-ar:
  isol: [yehbarree.isol.skl]
  fina: [yehbarree.fina.skl]
yehbarreeHamzaabove-ar:
  isol: [yehbarree.isol.skl, hamza.mrk]
  fina: [yehbarree.fina.skl, hamza.mrk]
zah-ar:
  isol: [tah.isol.skl, dotabove.mrk]
  init: [tah.init.skl, dotabove.mrk]
  medi: [tah.medi.skl, dotabove.mrk]
  fina: [tah.fina.skl, dotabove.mrk]
zain-ar:
  isol: [reh.isol.skl, dotabove.mrk]
  fina: [reh.fina.skl, dotabove.mrk]
